(provide 'autoloads)

;; C-u 3 M-x sort-fields
(autoload 'bs-cycle-next "bs" "cycle to next buffer" t)
(autoload 'bs-cycle-previous "bs" "cycle to previous buffer" t)
(autoload 'bs-show "bs" "menu for selecting and displaying buffers" t)
(autoload 'european-calendar "calendar")
(autoload 'idl-mode "cc-mode" "IDL mode" t)
(autoload 'cperl-mode "cperl-mode" "alternative Perl-mode" t)
(autoload 'cperl-perldoc "cperl-mode" "alternative Perl-mode" t)
(autoload 'cpplint "cpplint" nil t)
(autoload 'dired-jump "dired-x" nil t)
(autoload 'ediff "ediff" nil t)
(autoload 'ediff-buffers "ediff" nil t)
(autoload 'ediff-files "ediff" nil t)
(autoload 'edit-env "edit-env" nil t)
(autoload 'hl-tags-mode "hl-tags-mode" nil t)
(autoload 'mail-abbrevs-setup "mailabbrev" nil t)
(autoload 'inferior-moz-mode "moz" "MozRepl Inferior Mode" t)
(autoload 'inferior-moz-process "moz" "MozRepl Inferior Mode" t)
(autoload 'moz-minor-mode "moz" "Mozilla Minor and Inferior Mozilla Modes" t)
(autoload 'no-word "no-word" "word to txt")
(autoload 'py-shell "python-mode" "Python Mode." t)
(autoload 'python-mode "python-mode" "Python Mode." t)
(autoload 'shell-toggle "shell-toggle" "Toggles between the *shell* buffer and whatever buffer you are editing." t)
(autoload 'shell-toggle-cd "shell-toggle" "Pops up a shell-buffer and insert a \"cd <file-dir>\" command." t)
(autoload 'sc-cite-original "supercite" nil t)
(autoload 'typing-of-emacs "typing" "The Typing Of Emacs, a game." t)
(autoload 'whitespace-mode "whitespace" "Toggle whitespace visualization." t)
(autoload 'whitespace-toggle-options "whitespace" "Toggle local `whitespace-mode' options." t)


;; C-u 4 M-x sort-fields
;; (autoload 'css-mode "css-mode" t)
;; (autoload 'diff-mode "diff-mode" nil t)
;; (autoload 'inf-ruby "inf-ruby" nil t)
;; (autoload 'run-ruby "inf-ruby" nil t)
;; (autoload 'hg-status "mercurial" nil t)
;; (autoload 'php-mode "php-mode" "Major mode for editing PHP code." t)
;; (autoload 'plsql-mode "plsql" "Programming support mode for PL/SQL code." t)
;; (autoload 'ps-print-buffer "ps-print")
;; (autoload 'ps-print-buffer-with-faces "ps-print")
;; (autoload 'ruby-mode "ruby-mode" nil t)
;; (autoload 'scss-mode "scss-mode" t)
;; (autoload 'sh-mode "sh-script" "Shell edition mode" t)
;; (autoload 'sqlplus "sqlplus" "Start a new SQL*Plus session." t)
;; (autoload 'web-mode "web-mode" t)
